### ISSUE TITLE
Troubles building from the rust branch on Linux

### ISSUE THREAD

**Issue by danieldeankon** [agerasev/hypertrace#2]
See https://github.com/agerasev/hypertrace/issues/1 for computer specifications

Switched to the rust branch of this repository, made nightly (1.51 at time of writing) the default toolchain. Then:
```
git submodule init
git submodule update
cargo test
```
Output: [temp.txt](https://github.com/agerasev/hypertrace/files/5879808/temp.txt)
I then run `sudo apt-get install libgtest-dev` to install gtest. Installs without a hitch, and running `cargo test` eventually sees all 96 tests pass.

The instructions in the readme in the rust branch are incorrect, e.g. `./script/run.sh hyperbolic main` refers to a script that has been moved into another directory. I was not able to get it to run using the script, and neither was I able to make the rust project produce an executable (but `cargo build` did compile things). Not clear where to proceed from here.

**Comment by agerasev** [comment]
The `rust` branch is in progress currently and can not compile.

**Comment by danieldeankon** [comment]
I see. Since it's not expected to work in the first place, I'll close this issue.
